# Generated by Django 5.1.6 on 2025-02-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatarUrl',
            field=models.URLField(default='https://static.vecteezy.com/system/resources/previews/009/292/244/non_2x/default-avatar-icon-of-social-media-user-vector.jpg'),
        ),
    ]
